site_name: github blog
site_dir: ../usmile.github.com/
theme: bootstrap
docs_dir: docs
markdown_extensions: [toc, tables]
pages: 
  - [                        index.md,               首页]
  - [                 ./notes/bash.md,               笔记]
  - [                  ./notes/git.md,               笔记]
  - [               ./notes/python.md,               笔记]
  - [               ./notes/readme.md,               笔记]
  - [               ./notes/vmware.md,               笔记]
  - [        ./translate/datastore.md,               翻译]
  - [  ./translate/zookeeper_paper.md,               翻译]
  - [                        about.md,               关于]
